"use client";
import { Mail, ArrowUpRight, ShieldCheck, FileText } from "lucide-react";
import Link from "next/link";
export default function IntegrationsPage() {
  return <div className="workspace-page !max-w-[900px]"><p className="eyebrow mb-3">Bring your work together</p><h1 className="page-heading">Connections</h1><p className="mt-3 text-sm leading-6 text-[var(--app-muted)]">Manage the sources your agent can access.</p>
    <section className="mt-9 border-y border-[var(--app-line)] py-7"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-[var(--app-line)] bg-[var(--app-surface)]"><Mail size={20} strokeWidth={1.5} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Gmail</h2><span className="rounded-md border border-[var(--app-line)] px-2 py-1 text-[11px] text-[var(--app-muted)]">Not connected</span></div><p className="mt-2 text-sm leading-6 text-[var(--app-secondary)]">Find relevant opportunities and keep recruiter conversations in one place.</p><div className="mt-5 rounded-lg bg-[var(--app-subtle)] p-4"><p className="text-xs font-medium">Live connections are not available in this preview.</p><p className="mt-1 text-xs leading-5 text-[var(--app-muted)]">The inbox contains sample conversations. No Google account has been authorized and no messages are being read or sent.</p></div></div></div></section>
    <section className="border-b border-[var(--app-line)] py-7"><div className="flex gap-4"><FileText size={20} className="mt-1 shrink-0 text-[var(--app-muted)]" /><div><h2 className="text-sm font-semibold">Your documents</h2><p className="mt-2 text-sm leading-6 text-[var(--app-muted)]">Add CVs directly to this browser while you explore the workspace.</p><Link href="/dashboard/cvs" className="mt-4 inline-flex items-center gap-2 text-xs font-medium">Manage documents <ArrowUpRight size={14} /></Link></div></div></section>
    <div className="mt-7 flex gap-3 text-[var(--app-muted)]"><ShieldCheck size={18} className="shrink-0" /><p className="text-xs leading-5">When live connections are available, you’ll review the requested permissions before granting access.</p></div>
  </div>;
}
