import { z } from "zod";
import { registerSchema, loginSchema, emailSchema, tokenSchema, resetPasswordSchema } from "./modules/auth/auth.schema.js";
import { profileSchema } from "./modules/profile/profile.schema.js";
import { profileFactInputSchema } from "./modules/profile/profile-fact.schema.js";
import { policySchema } from "./modules/agent/agent.schema.js";
import { cvEditSchema } from "./modules/cvs/cv.schema.js";
import { extractedCvProfileSchema } from "./modules/cvs/cv-extraction.schema.js";
import { discoveredJobSchema, jobSearchSchema, saveJobSchema } from "./modules/jobs/job.schema.js";
import { opportunityInputSchema, opportunityUpdateSchema, manualStatusSchema } from "./modules/opportunities/opportunity.schema.js";
import { extractInputSchema, extractedOpportunitySchema } from "./modules/opportunities/opportunity-extraction.schema.js";

const schemaOf = (schema: z.ZodType) => z.toJSONSchema(schema, { io: "input" });
const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const body = (schema: object, example?: object) => ({ required: true, content: { "application/json": { schema, ...(example ? { example } : {}) } } });
const result = (description: string, schema?: object, example?: object) => ({ description, ...(schema ? { content: { "application/json": { schema, ...(example ? { example } : {}) } } } : {}) });
const error = (codes: string[], description: string) => result(
  `${description} Codes: ${codes.map(code => `\`${code}\``).join(", ")}.`,
  { allOf: [ref("ApiError"), { type: "object", properties: { error: { type: "string", enum: codes } } }] },
  codes[0] === "internal_error" ? { error: "internal_error", traceId: "a1b2c3d4-0000-4000-8000-000000000099" } : { error: codes[0] },
);
const invalid = error(["invalid_input", "invalid_json"], "Invalid request. `error` is `invalid_input` or `invalid_json`; validation failures include `issues`.");
const unauthorized = error(["unauthorized"], "No valid Pursio session cookie.");
const invalidOrigin = error(["invalid_origin"], "Mutation Origin does not equal WEB_ORIGIN.");
const internal = error(["internal_error"], "Unexpected server error. Response includes `traceId` for support.");
const protectedGet = { "401": unauthorized, "500": internal };
const protectedMutation = { "400": invalid, "401": unauthorized, "403": invalidOrigin, "500": internal };
const uuid = { type: "string", format: "uuid" };
const dateTime = { type: "string", format: "date-time" };
const nullableText = { type: ["string", "null"] };
const id = { name: "id", in: "path", required: true, description: "Resource ID (UUID).", schema: uuid };
const userExample = { id: "a1b2c3d4-0000-4000-8000-000000000001", email: "alex@example.com", displayName: "Alex" };
const cvExample = { id: "a1b2c3d4-0000-4000-8000-000000000010", familyId: "a1b2c3d4-0000-4000-8000-000000000011", label: "Full-stack", fileName: "alex-cv.pdf", version: 1, isDefault: true, roleFocus: "Full-stack engineer", byteSize: 245760, mimeType: "application/pdf", uploadedAt: "2026-09-27T12:00:00.000Z", status: "parsing" };
const opportunityExample = { id: "a1b2c3d4-0000-4000-8000-000000000020", userId: userExample.id, type: "JOB", companyName: "Acme", companyDomain: null, title: "Backend Engineer", description: "Build APIs and services.", location: "Remote", workMode: "remote", compensation: null, deadline: null, source: "manual", sourceUrl: "https://acme.example/jobs/backend", status: "NEW", discoveredAt: "2026-09-27T12:00:00.000Z", updatedAt: "2026-09-27T12:00:00.000Z" };
const opportunityInputExample = { type: "JOB", companyName: "Acme", title: "Backend Engineer", description: "Build APIs and services.", location: "Remote", workMode: "remote", sourceUrl: "https://acme.example/jobs/backend" };
const profileExample = { headline: "Backend engineer", summary: "I build APIs.", yearsExperience: 4, targetRoles: ["Backend Engineer"], skills: ["Node.js", "PostgreSQL"], locations: ["Remote"], workModes: ["remote"], compensationCurrency: "USD", links: { github: "https://github.com/alex" } };
const policyExample = { globalMode: "observe", minMatchScore: 70, autoSendMinScore: 85, maxDailyOutreach: 0, requireApprovalFor: ["salary_negotiation"], exclusions: [] };
const cvUpload = { required: true, content: { "multipart/form-data": { schema: { type: "object", required: ["file", "label"], properties: { file: { type: "string", format: "binary", description: "PDF or DOCX, at most 10 MiB." }, label: { type: "string", minLength: 1, maxLength: 100 }, roleFocus: { type: "string", maxLength: 160, description: "Optional role label." } } } } } };
const list = (name: string) => ({ type: "object", required: ["items"], properties: { items: { type: "array", items: ref(name) } } });
const redirect = (description: string) => ({ description, headers: { Location: { description: "Destination URL", schema: { type: "string", format: "uri" } } } });
const endpoint = (tag: string, operationId: string, summary: string, responses: object, extras: object = {}) => ({ tags: [tag], operationId, summary, responses, ...extras });

export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Pursio API",
    version: "0.1.0",
    description: `## Frontend quick start
1. Use the API origin as your base URL. For browser requests use \`credentials: "include"\`.
2. Register with \`POST /api/auth/register\`, pass the emailed token to \`POST /api/auth/verify-email\`, then log in. Alternatively, navigate the browser to \`GET /api/auth/google/start\`.
3. The backend sets an HttpOnly \`pursio_session\` cookie. Call \`GET /api/auth/me\` to restore the user after refresh or Google redirect.
4. For POST, PUT, PATCH, and DELETE, the browser's \`Origin\` must match the configured frontend origin exactly. Send JSON unless an operation specifies multipart form data.

## Errors
Errors are JSON: \`{ "error": "code" }\`. Validation errors also have \`issues\`; unexpected 500 errors have \`traceId\`. A 401 means the frontend should show sign-in. A 403 \`invalid_origin\` means the frontend origin configuration is wrong. Google callback failures redirect to the frontend with an \`error\` query parameter.

Swagger's **Try it out** works for browser requests only when this docs page is served from the allowed frontend origin. For redirect routes, navigate the browser to the URL instead of using Try it out.`,
  },
  servers: [{ url: "/", description: "Current Pursio API origin" }],
  tags: [
    { name: "Health", description: "Process and required-service readiness." },
    { name: "Account", description: "Email registration, verification, login, recovery, and session." },
    { name: "Google sign-in", description: "Full-page redirects for Google sign-in and explicit account linking." },
    { name: "Gmail", description: "Separate read-only Gmail consent and on-demand review of recent job-related inbox messages." },
    { name: "Dashboard", description: "Overview data for the signed-in user." },
    { name: "Profile", description: "Professional profile and self-reported facts." },
    { name: "CVs", description: "Private PDF/DOCX CVs, distinct CV families, and versions." },
    { name: "Job search", description: "Live provider-backed job discovery, with explicit saving to the opportunity pipeline." },
    { name: "Opportunities", description: "Manual opportunity pipeline and reviewable AI extraction." },
    { name: "Agent", description: "Autonomy policy and pause control." },
    { name: "Activity", description: "Recent audit events." },
  ],
  security: [{ sessionCookie: [] }],
  components: {
    securitySchemes: { sessionCookie: { type: "apiKey", in: "cookie", name: "pursio_session", description: "HttpOnly cookie set by login or Google redirect. Browser fetch must use credentials: include." } },
    schemas: {
      ApiError: { type: "object", required: ["error"], properties: { error: { type: "string", description: "Stable machine-readable error code." }, issues: { type: "array", description: "Zod validation issues; present for invalid_input.", items: { type: "object", additionalProperties: true } }, traceId: { type: "string", format: "uuid", description: "Present for unexpected 500 errors." } } },
      Message: { type: "object", required: ["message"], properties: { message: { type: "string" } } },
      AuthUser: { type: "object", required: ["id", "email", "displayName"], properties: { id: uuid, email: { type: "string", format: "email" }, displayName: { type: "string" } } },
      CurrentUser: { type: "object", required: ["id", "email", "displayName", "timezone"], properties: { id: uuid, email: { type: "string", format: "email" }, displayName: { type: "string" }, timezone: { type: "string" } } },
      ProfileInput: schemaOf(profileSchema),
      ProfileFact: { type: "object", required: ["id", "type", "value", "verified", "evidenceSource"], properties: { id: uuid, userId: uuid, type: { type: "string" }, value: { type: "string" }, verified: { type: "boolean" }, evidenceSource: { type: "string" }, createdAt: dateTime } },
      ProfileWithFacts: { type: "object", required: [...(schemaOf(profileSchema) as { required?: string[] }).required ?? [], "facts"], properties: { ...(schemaOf(profileSchema) as { properties?: object }).properties, facts: { type: "array", items: ref("ProfileFact") } } },
      AgentPolicyInput: schemaOf(policySchema),
      AgentPolicyState: { type: "object", required: [...(schemaOf(policySchema) as { required?: string[] }).required ?? [], "paused", "version"], properties: { ...(schemaOf(policySchema) as { properties?: object }).properties, paused: { type: "boolean" }, version: { type: "integer" } } },
      CV: { type: "object", required: ["id", "familyId", "label", "fileName", "version", "isDefault", "roleFocus", "byteSize", "mimeType", "uploadedAt", "status"], properties: { id: uuid, familyId: uuid, label: { type: "string" }, fileName: { type: "string" }, version: { type: "integer" }, isDefault: { type: "boolean" }, roleFocus: { type: "string" }, byteSize: { type: "integer" }, mimeType: { type: "string", enum: ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"] }, uploadedAt: dateTime, status: { type: "string", enum: ["ready", "parsing", "error"] } } },
      CvExtractedProfile: schemaOf(extractedCvProfileSchema),
      CvExtraction: { type: "object", required: ["status", "text", "profile", "error"], properties: { status: { type: "string", enum: ["parsing", "ready", "error"] }, text: nullableText, profile: { anyOf: [ref("CvExtractedProfile"), { type: "null" }] }, error: nullableText } },
      DiscoveredJob: schemaOf(discoveredJobSchema),
      JobSearchInput: schemaOf(jobSearchSchema),
      Opportunity: { type: "object", required: ["id", "userId", "type", "companyName", "companyDomain", "title", "description", "location", "workMode", "compensation", "deadline", "source", "sourceUrl", "status", "discoveredAt", "updatedAt"], properties: { id: uuid, userId: uuid, type: { type: "string", enum: ["JOB", "CLIENT", "INBOUND"] }, companyName: { type: "string" }, companyDomain: nullableText, title: { type: "string" }, description: { type: "string" }, location: nullableText, workMode: nullableText, compensation: { type: ["object", "null"], properties: { min: { type: "number" }, max: { type: "number" }, currency: { type: "string" } } }, deadline: { type: ["string", "null"], format: "date-time" }, source: { type: "string" }, sourceUrl: nullableText, status: { type: "string", enum: ["NEW", "QUALIFIED", "SKIPPED", "PREPARED", "PENDING_APPROVAL", "APPLIED", "CONTACTED", "REPLIED", "INTERVIEW", "INTERESTED", "OFFER", "WON", "REJECTED", "LOST", "CLOSED"] }, discoveredAt: dateTime, updatedAt: dateTime } },
      GmailStatus: { type: "object", required: ["connected", "email", "connectedAt", "lastSyncedAt"], properties: { connected: { type: "boolean" }, email: nullableText, connectedAt: { type: ["string", "null"], format: "date-time" }, lastSyncedAt: { type: ["string", "null"], format: "date-time" } } },
      GmailMessage: { type: "object", required: ["id", "threadId", "subject", "sender", "snippet", "receivedAt"], properties: { id: uuid, threadId: { type: "string" }, subject: { type: "string" }, sender: { type: "string" }, snippet: { type: "string" }, receivedAt: dateTime } },
      AuditEvent: { type: "object", required: ["id", "userId", "actor", "eventType", "entityType", "entityId", "traceId", "details", "createdAt"], properties: { id: uuid, userId: { type: ["string", "null"], format: "uuid" }, actor: { type: "string" }, eventType: { type: "string" }, entityType: { type: "string" }, entityId: { type: ["string", "null"], format: "uuid" }, traceId: uuid, details: { type: "object", additionalProperties: true }, createdAt: dateTime } },
      Dashboard: { type: "object", required: ["today", "pipeline", "agent", "recentOpportunities", "recentActivity"], properties: { today: { type: "object", required: ["startsAt", "timezone", "opportunitiesFound"], properties: { startsAt: dateTime, timezone: { const: "UTC" }, opportunitiesFound: { type: "integer" } } }, pipeline: { type: "object", required: ["total", "byStatus"], properties: { total: { type: "integer" }, byStatus: { type: "object", additionalProperties: { type: "integer" } } } }, agent: { type: "object", required: ["paused", "mode"], properties: { paused: { type: "boolean" }, mode: { type: "string", enum: ["observe", "prepare", "auto"] } } }, recentOpportunities: { type: "array", items: { type: "object", required: ["id", "type", "companyName", "title", "status", "updatedAt"], properties: { id: uuid, type: { type: "string", enum: ["JOB", "CLIENT", "INBOUND"] }, companyName: { type: "string" }, title: { type: "string" }, status: { type: "string" }, updatedAt: dateTime } } }, recentActivity: { type: "array", items: { type: "object", required: ["id", "eventType", "entityType", "entityId", "createdAt"], properties: { id: uuid, eventType: { type: "string" }, entityType: { type: "string" }, entityId: { type: ["string", "null"], format: "uuid" }, createdAt: dateTime } } } } },
    },
  },
  paths: {
    "/health/live": { get: endpoint("Health", "getLiveness", "Check that the API process is running", { "200": result("Process is running.", { type: "object", properties: { status: { const: "ok" } } }, { status: "ok" }) }, { security: [] }) },
    "/health/ready": { get: endpoint("Health", "getReadiness", "Check PostgreSQL and Redis", { "200": result("Both required services respond.", { type: "object", properties: { status: { const: "ok" } } }, { status: "ok" }), "503": error(["dependency_unavailable"], "PostgreSQL or Redis is unavailable.") }, { security: [] }) },

    "/api/auth/register": { post: endpoint("Account", "register", "Create account and request verification email", { "202": result("Generic response, including when the address already exists.", ref("Message"), { message: "If the address can be registered, a verification email has been sent." }), "400": invalid, "403": invalidOrigin, "429": error(["rate_limited"], "Too many attempts."), "500": internal, "503": error(["email_not_configured"], "Email sender is not configured.") }, { security: [], requestBody: body(schemaOf(registerSchema), { email: "alex@example.com", password: "long-secret-passphrase", displayName: "Alex", timezone: "UTC" }), description: "After receiving the email, take its token and call `/api/auth/verify-email`. The frontend owns `/auth/verify-email`." }) },
    "/api/auth/verify-email": { post: endpoint("Account", "verifyEmail", "Verify email using the emailed token", { "204": result("Email verified; response has no body."), "400": error(["invalid_or_expired_token", "invalid_input"], "Token is invalid, expired, or already used."), "403": invalidOrigin, "429": error(["rate_limited"], "Too many attempts."), "500": internal }, { security: [], requestBody: body(schemaOf(tokenSchema), { token: "a".repeat(64) }) }) },
    "/api/auth/resend-verification": { post: endpoint("Account", "resendVerification", "Request a new verification email", { "202": result("Generic response.", ref("Message"), { message: "If verification is needed, an email has been sent." }), "400": invalid, "403": invalidOrigin, "429": error(["rate_limited"], "Too many attempts."), "500": internal, "503": error(["email_not_configured"], "Email sender is not configured.") }, { security: [], requestBody: body(schemaOf(emailSchema), { email: "alex@example.com" }) }) },
    "/api/auth/forgot-password": { post: endpoint("Account", "forgotPassword", "Request password reset email", { "202": result("Generic response.", ref("Message"), { message: "If the account exists, a reset email has been sent." }), "400": invalid, "403": invalidOrigin, "429": error(["rate_limited"], "Too many attempts."), "500": internal, "503": error(["email_not_configured"], "Email sender is not configured.") }, { security: [], requestBody: body(schemaOf(emailSchema), { email: "alex@example.com" }) }) },
    "/api/auth/reset-password": { post: endpoint("Account", "resetPassword", "Reset password and revoke existing sessions", { "204": result("Password changed; response has no body."), "400": error(["invalid_or_expired_token", "invalid_input"], "Token is invalid, expired, or already used."), "403": invalidOrigin, "429": error(["rate_limited"], "Too many attempts."), "500": internal }, { security: [], requestBody: body(schemaOf(resetPasswordSchema), { token: "a".repeat(64), password: "new-long-secret-passphrase" }) }) },
    "/api/auth/login": { post: endpoint("Account", "login", "Sign in with email and password", { "200": result("Session cookie and user.", { type: "object", required: ["user"], properties: { user: ref("AuthUser") } }, { user: userExample }), "400": invalid, "401": error(["invalid_credentials"], "Email or password is incorrect."), "403": error(["email_not_verified", "invalid_origin"], "Account is unverified or mutation origin is invalid."), "429": error(["rate_limited"], "Too many attempts."), "500": internal }, { security: [], requestBody: body(schemaOf(loginSchema), { email: "alex@example.com", password: "long-secret-passphrase" }), description: "The response sets `pursio_session` as an HttpOnly cookie. Store the returned user in frontend state; the browser stores the cookie." }) },
    "/api/auth/me": { get: endpoint("Account", "getCurrentUser", "Restore signed-in user", { "200": result("Current account.", { type: "object", required: ["user"], properties: { user: ref("CurrentUser") } }, { user: { ...userExample, timezone: "UTC" } }), ...protectedGet }) },
    "/api/auth/logout": { post: endpoint("Account", "logout", "Revoke current session", { "204": result("Logged out; response has no body."), ...protectedMutation }) },

    "/api/auth/google/start": { get: endpoint("Google sign-in", "startGoogleSignIn", "Navigate browser to start Google sign-in", { "302": redirect("Redirect to Google. Sets a short-lived HttpOnly flow cookie."), "429": error(["rate_limited"], "Too many attempts."), "500": internal, "503": error(["google_auth_not_configured"], "Google OAuth settings are missing.") }, { security: [], description: "Use `window.location.assign(API_BASE + '/api/auth/google/start')`. This is full-page navigation, not a fetch request." }) },
    "/api/auth/google/callback": { get: endpoint("Google sign-in", "googleCallback", "Google returns authorization code to backend", { "303": redirect("Redirect to `${WEB_ORIGIN}/auth/google/callback`. On success sets session cookie. On failure appends `?error=google_sign_in_failed`, `?error=account_link_required`, or `?error=session_expired`."), "500": internal }, { security: [], description: "Register the exact absolute URL of this path as `GOOGLE_REDIRECT_URI` in Google Cloud. The frontend never calls this endpoint itself. After the final redirect, call `/api/auth/me` to obtain the user." }) },
    "/api/auth/google/link/start": { get: endpoint("Google sign-in", "startGoogleLink", "Navigate browser to link Google to current account", { "302": redirect("Redirect to Google."), ...protectedGet, "503": error(["google_auth_not_configured"], "Google OAuth settings are missing.") }, { description: "Requires an existing Pursio session. Google email must match the current account. Success returns to frontend with `?linked=1`." }) },

    "/api/integrations/gmail/start": { get: endpoint("Gmail", "startGmailConnection", "Navigate browser to connect Gmail", { "302": redirect("Redirect to Google for read-only Gmail consent."), ...protectedGet, "503": error(["gmail_not_configured"], "Gmail settings are missing.") }, { description: "Use full-page navigation with the current Pursio session cookie. Register `GMAIL_REDIRECT_URI` in Google Cloud. Gmail consent is separate from Google sign-in." }) },
    "/api/integrations/gmail/callback": { get: endpoint("Gmail", "gmailCallback", "Google returns Gmail consent to backend", { "303": redirect("Redirects to `${WEB_ORIGIN}/settings/integrations/gmail` with `?connected=1` or `?error=gmail_connection_failed`, `?error=gmail_account_in_use`, or `?error=session_expired`."), "500": internal }, { security: [], description: "Google calls this route. The frontend must not call it. The same Pursio session used at start must still be active." }) },
    "/api/integrations/gmail/status": { get: endpoint("Gmail", "getGmailStatus", "Read Gmail connection status", { "200": result("No token is returned.", ref("GmailStatus"), { connected: true, email: "alex@gmail.com", connectedAt: "2026-09-28T12:00:00.000Z", lastSyncedAt: null }), ...protectedGet }) },
    "/api/integrations/gmail/sync": { post: endpoint("Gmail", "syncGmail", "Scan recent job-related inbox messages on demand", { "200": result("Stored review candidates.", { type: "object", required: ["matched", "items"], properties: { matched: { type: "integer" }, items: { type: "array", items: ref("GmailMessage") } } }, { matched: 1, items: [{ id: "a1b2c3d4-0000-4000-8000-000000000060", threadId: "18abcd", subject: "Interview invitation", sender: "Recruiter <jobs@example.com>", snippet: "We would like to invite you...", receivedAt: "2026-09-28T12:00:00.000Z" }] }), ...protectedMutation, "409": error(["gmail_not_connected"], "Connect Gmail first."), "429": error(["gmail_sync_rate_limited"], "Wait five minutes between syncs."), "502": error(["gmail_unavailable"], "Gmail API unavailable."), "503": error(["gmail_not_configured", "gmail_token_unavailable"], "Gmail configuration or saved token unavailable.") }, { description: "Looks at up to 50 inbox messages from the last 30 days. Only subject, sender, preview, and thread ID are stored. No sending, application, AI action, or automatic opportunity creation occurs." }) },
    "/api/integrations/gmail/messages": { get: endpoint("Gmail", "listGmailMessages", "List job-related Gmail review candidates", { "200": result("Most recent 100 candidates.", list("GmailMessage"), { items: [] }), ...protectedGet, "409": error(["gmail_not_connected"], "Connect Gmail first.") }) },
    "/api/integrations/gmail/connection": { delete: endpoint("Gmail", "disconnectGmail", "Disconnect Gmail and delete stored message previews", { "204": result("Disconnected; no body."), ...protectedMutation }, { description: "Pursio deletes the stored refresh token and message previews, then asks Google to revoke the token." }) },

    "/api/dashboard": { get: endpoint("Dashboard", "getDashboard", "Get pipeline overview", { "200": result("Overview for the current user.", ref("Dashboard"), { today: { startsAt: "2026-09-27T00:00:00.000Z", timezone: "UTC", opportunitiesFound: 1 }, pipeline: { total: 1, byStatus: { NEW: 1 } }, agent: { paused: true, mode: "observe" }, recentOpportunities: [{ id: opportunityExample.id, type: "JOB", companyName: "Acme", title: "Backend Engineer", status: "NEW", updatedAt: opportunityExample.updatedAt }], recentActivity: [] }), ...protectedGet }, { description: "`today` uses UTC. Pipeline counts reflect stored opportunities, not AI scores or completed automation." }) },
    "/api/profile": {
      get: endpoint("Profile", "getProfile", "Get professional profile and facts", { "200": result("Profile with facts.", ref("ProfileWithFacts"), { ...profileExample, facts: [] }), ...protectedGet }),
      put: endpoint("Profile", "updateProfile", "Replace entire professional profile", { "200": result("Saved profile fields.", ref("ProfileInput"), profileExample), ...protectedMutation }, { requestBody: body(ref("ProfileInput"), profileExample), description: "PUT replaces the full profile. Send all required fields, including empty arrays/strings where appropriate." }),
    },
    "/api/profile/facts": { post: endpoint("Profile", "addProfileFact", "Add a self-reported profile fact", { "201": result("Created fact. It starts unverified.", ref("ProfileFact"), { id: "a1b2c3d4-0000-4000-8000-000000000030", userId: userExample.id, type: "skill", value: "PostgreSQL", evidenceSource: "Self-reported", verified: false, createdAt: "2026-09-27T12:00:00.000Z" }), ...protectedMutation }, { requestBody: body(schemaOf(profileFactInputSchema), { type: "skill", value: "PostgreSQL" }) }) },
    "/api/profile/facts/{id}": { delete: endpoint("Profile", "deleteProfileFact", "Delete own profile fact", { "204": result("Deleted; no body."), ...protectedMutation, "404": error(["not_found"], "Fact does not exist for this user.") }, { parameters: [id] }) },

    "/api/cvs": {
      get: endpoint("CVs", "listCvs", "List uploaded CV versions", { "200": result("CV versions, newest first.", list("CV"), { items: [cvExample] }), ...protectedGet }),
      post: endpoint("CVs", "uploadCv", "Upload a new distinct CV", { "201": result("CV metadata.", ref("CV"), cvExample), ...protectedMutation, "409": error(["duplicate_cv", "cv_upload_expired"], "Duplicate content or expired upload reservation."), "413": error(["cv_quota_exceeded", "invalid_upload"], "10 distinct CVs, 100 MiB total, or 10 MiB file limit exceeded."), "415": error(["unsupported_cv_type"], "Only detected PDF or DOCX files are accepted."), "503": error(["cloudinary_not_configured"], "Cloudinary storage unavailable.") }, { requestBody: cvUpload, description: "Send `multipart/form-data` with file and label. A new CV counts toward the 10 distinct-CV limit. Every version counts toward total storage. The response has `status: parsing`; poll `/api/cvs/{id}/extraction`." }),
    },
    "/api/cvs/{id}": {
      get: endpoint("CVs", "getCv", "Get one CV version's metadata", { "200": result("CV metadata.", ref("CV"), cvExample), ...protectedGet, "404": error(["not_found"], "CV not found.") }, { parameters: [id] }),
      patch: endpoint("CVs", "updateCvMetadata", "Edit a CV version’s label or role focus", { "200": result("Updated CV metadata.", ref("CV"), cvExample), ...protectedMutation, "404": error(["not_found"], "CV not found.") }, { parameters: [id], requestBody: body(schemaOf(cvEditSchema), { label: "Full-stack CV", roleFocus: "Full-stack developer" }), description: "Send either field or both. `roleFocus` is user-defined; an empty string clears it. This changes the selected version only." }),
      delete: endpoint("CVs", "deleteCv", "Delete a CV version and its stored file", { "204": result("Deleted; no body."), ...protectedMutation, "404": error(["cv_not_found"], "CV not found.") }, { parameters: [id] }),
    },
    "/api/cvs/{id}/extraction": { get: endpoint("CVs", "getCvExtraction", "Read CV extraction state and reviewable profile", { "200": result("Parsing returns null text/profile/error; ready returns text/profile; error returns a stable error code.", ref("CvExtraction"), { status: "ready", text: "Alex Smith\nBackend Engineer\nSkills: Node.js", profile: { name: { value: "Alex Smith", evidence: "Alex Smith" }, headline: { value: "Backend Engineer", evidence: "Backend Engineer" }, skills: [{ value: "Node.js", evidence: "Skills: Node.js" }], experience: [], education: [] }, error: null }), ...protectedGet, "404": error(["cv_not_found"], "CV not found for this account.") }, { parameters: [id], description: "Poll while status is `parsing`. Extracted claims are unverified and must be reviewed before use. Error codes include `no_extractable_text`, `cv_too_many_pages`, `cv_text_too_large`, and `extraction_failed`." }) },
    "/api/cvs/{id}/extraction/retry": { post: endpoint("CVs", "retryCvExtraction", "Retry failed CV extraction", { "202": result("Requeued CV metadata with status parsing.", ref("CV"), cvExample), ...protectedMutation, "404": error(["cv_not_found"], "CV not found for this account."), "409": error(["cv_extraction_not_failed"], "Only a failed extraction can be retried.") }, { parameters: [id], description: "No request body. Poll GET `/api/cvs/{id}/extraction` after retrying." }) },
    "/api/cvs/{id}/versions": { post: endpoint("CVs", "uploadCvVersion", "Upload a new version of an existing CV", { "201": result("New version metadata.", ref("CV"), { ...cvExample, version: 2 }), ...protectedMutation, "404": error(["cv_not_found"], "Original CV not found."), "409": error(["duplicate_cv", "cv_upload_expired"], "Duplicate content or expired upload reservation."), "413": error(["cv_quota_exceeded", "invalid_upload"], "Storage or file-size limit exceeded."), "415": error(["unsupported_cv_type"], "Only detected PDF or DOCX files are accepted."), "503": error(["cloudinary_not_configured"], "Cloudinary storage unavailable.") }, { parameters: [id], requestBody: cvUpload, description: "`id` is any version in the CV family. This increments the family version and does not use another distinct-CV slot. Omit `roleFocus` to inherit it from the selected version." }) },
    "/api/cvs/{id}/default": { post: endpoint("CVs", "setDefaultCv", "Make this CV version the default", { "200": result("Updated CV metadata.", ref("CV"), cvExample), ...protectedMutation, "404": error(["not_found"], "CV not found.") }, { parameters: [id] }) },
    "/api/cvs/{id}/download": { get: endpoint("CVs", "downloadCv", "Redirect to temporary signed CV download", { "303": redirect("Signed Cloudinary URL, valid for 60 seconds."), ...protectedGet, "404": error(["cv_not_found"], "CV not found."), "503": error(["cloudinary_not_configured"], "Cloudinary storage unavailable.") }, { parameters: [id], description: "Browser navigation follows the redirect. For fetch, use `redirect: 'follow'` and appropriate credentials on the API request." }) },

    "/api/jobs/sources": { get: endpoint("Job search", "getJobSources", "See available job search coverage", { "200": result("Remote search is always available. Regional countries are those with configured Jooble keys.", { type: "object", required: ["remote", "regionalCountries"], properties: { remote: { const: "himalayas" }, regionalCountries: { type: "array", items: { type: "string", pattern: "^[A-Z]{2}$" } } } }, { remote: "himalayas", regionalCountries: ["NG"] }), ...protectedGet }) },
    "/api/jobs/search": { post: endpoint("Job search", "searchJobs", "Search live job listings", { "200": result("Search results are not saved. `searchId` expires after 30 minutes.", { type: "object", required: ["searchId", "source", "attribution", "items"], properties: { searchId: uuid, source: { type: "string", enum: ["himalayas", "jooble"] }, attribution: { type: "string" }, items: { type: "array", items: ref("DiscoveredJob") } } }, { searchId: "a1b2c3d4-0000-4000-8000-000000000050", source: "himalayas", attribution: "Jobs by Himalayas", items: [{ source: "himalayas", sourceId: "remote-job-123", title: "Backend Engineer", companyName: "Acme", description: "Build APIs with Node.js.", location: "Nigeria", workMode: "remote", sourceUrl: "https://himalayas.app/jobs/backend-engineer", publishedAt: "2026-09-27T12:00:00.000Z", attribution: "Himalayas" }] }), ...protectedMutation, "422": error(["job_region_not_configured"], "Hybrid/onsite search has no provider key configured for this country."), "429": error(["job_search_rate_limited"], "30 searches per user per hour."), "502": error(["job_source_unavailable"], "Upstream job source is unavailable or returned invalid data."), "503": error(["job_search_unavailable"], "Search cache is unavailable.") }, { requestBody: body(ref("JobSearchInput"), { keywords: "Backend Engineer", country: "NG", region: "Lagos", workMode: "remote", page: 1 }), description: "Use two-letter ISO country codes. `region` narrows regional Jooble searches; remote Himalayas searches use country eligibility and ignore region. Remote listings must show `attribution` and link to `sourceUrl`. Jooble hybrid results require an explicit hybrid mention; onsite results have `workMode: null` because Jooble does not verify onsite status. Review source details before applying." }) },
    "/api/jobs/save": { post: endpoint("Job search", "saveDiscoveredJob", "Save a selected result to the pipeline", { "201": result("New opportunity created.", { type: "object", required: ["created", "opportunity"], properties: { created: { type: "boolean" }, opportunity: ref("Opportunity") } }, { created: true, opportunity: { ...opportunityExample, source: "himalayas" } }), "200": result("Already saved; existing opportunity returned without changing its status.", { type: "object", required: ["created", "opportunity"], properties: { created: { type: "boolean" }, opportunity: ref("Opportunity") } }, { created: false, opportunity: { ...opportunityExample, source: "himalayas" } }), ...protectedMutation, "404": error(["job_not_in_search"], "Result was not in this user’s search."), "410": error(["job_search_expired"], "Search result expired; run the search again."), "503": error(["job_search_unavailable"], "Search cache is unavailable.") }, { requestBody: body(schemaOf(saveJobSchema), { searchId: "a1b2c3d4-0000-4000-8000-000000000050", sourceId: "remote-job-123" }), description: "Use `searchId` and an item’s `sourceId` from `/api/jobs/search`. A result can only be saved by the user who searched. Search results expire after 30 minutes." }) },

    "/api/opportunities": {
      get: endpoint("Opportunities", "listOpportunities", "List pipeline opportunities", { "200": result("Filtered list.", list("Opportunity"), { items: [opportunityExample] }), "400": invalid, ...protectedGet }, { parameters: [{ name: "type", in: "query", schema: { type: "string", enum: ["JOB", "CLIENT", "INBOUND"] } }, { name: "status", in: "query", schema: { type: "string", enum: ["NEW", "QUALIFIED", "SKIPPED", "PREPARED", "PENDING_APPROVAL", "APPLIED", "CONTACTED", "REPLIED", "INTERVIEW", "INTERESTED", "OFFER", "WON", "REJECTED", "LOST", "CLOSED"] } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 30 } }, { name: "offset", in: "query", schema: { type: "integer", minimum: 0, maximum: 10000, default: 0 } }] }),
      post: endpoint("Opportunities", "createOpportunity", "Create a manual opportunity", { "201": result("Created opportunity.", ref("Opportunity"), opportunityExample), ...protectedMutation, "409": error(["duplicate_opportunity"], "An opportunity with this canonical source URL already exists.") }, { requestBody: body(schemaOf(opportunityInputSchema), opportunityInputExample) }),
    },
    "/api/opportunities/extract": { post: endpoint("Opportunities", "extractOpportunity", "Extract a reviewable draft with Gemini", { "200": result("Draft only; not saved.", schemaOf(extractedOpportunitySchema), { type: "JOB", companyName: "Acme", title: "Backend Engineer", description: "Build APIs.", location: null, sourceUrl: null, unknowns: ["Compensation not specified"] }), ...protectedMutation, "429": error(["ai_daily_limit_reached"], "Daily extraction request limit reached."), "503": error(["gemini_not_configured"], "Gemini is not configured.") }, { requestBody: body(schemaOf(extractInputSchema), { sourceText: "Acme is hiring a Backend Engineer to build Node.js APIs with PostgreSQL. Apply through the careers page; compensation was not specified." }), description: "Pass 50–20,000 characters of job text. Review the returned draft and send it to `POST /api/opportunities` only if correct. This endpoint consumes one daily AI request even if the model fails." }) },
    "/api/opportunities/{id}": {
      get: endpoint("Opportunities", "getOpportunity", "Get one opportunity", { "200": result("Opportunity.", ref("Opportunity"), opportunityExample), ...protectedGet, "404": error(["not_found"], "Opportunity not found.") }, { parameters: [id] }),
      patch: endpoint("Opportunities", "updateOpportunity", "Edit a manual opportunity", { "200": result("Updated opportunity.", ref("Opportunity"), opportunityExample), ...protectedMutation, "404": error(["not_found"], "Not found or not a manual opportunity.") }, { parameters: [id], requestBody: body(schemaOf(opportunityUpdateSchema), { title: "Senior Backend Engineer" }) }),
      delete: endpoint("Opportunities", "deleteOpportunity", "Delete an opportunity", { "204": result("Deleted; no body."), ...protectedMutation, "404": error(["not_found"], "Opportunity not found for this user.") }, { parameters: [id] }),
    },
    "/api/opportunities/{id}/status": { post: endpoint("Opportunities", "setOpportunityStatus", "Change an opportunity’s status", { "200": result("Updated opportunity.", ref("Opportunity"), { ...opportunityExample, status: "QUALIFIED" }), ...protectedMutation, "404": error(["not_found"], "Opportunity not found for this user.") }, { parameters: [id], requestBody: body(schemaOf(manualStatusSchema), { status: "QUALIFIED" }) }) },

    "/api/agent/policy": {
      get: endpoint("Agent", "getAgentPolicy", "Get policy and pause state", { "200": result("Current policy.", ref("AgentPolicyState"), { ...policyExample, paused: true, version: 1 }), ...protectedGet }),
      put: endpoint("Agent", "updateAgentPolicy", "Replace policy settings", { "200": result("Saved policy fields; GET to refresh pause/version.", ref("AgentPolicyInput"), policyExample), ...protectedMutation }, { requestBody: body(ref("AgentPolicyInput"), policyExample), description: "PUT replaces the policy fields. Pause state is managed separately by `/pause` and `/resume`." }),
    },
    "/api/agent/pause": { post: endpoint("Agent", "pauseAgent", "Pause the agent", { "200": result("Agent paused.", { type: "object", required: ["paused"], properties: { paused: { const: true } } }, { paused: true }), ...protectedMutation }) },
    "/api/agent/resume": { post: endpoint("Agent", "resumeAgent", "Resume the agent", { "200": result("Agent resumed.", { type: "object", required: ["paused"], properties: { paused: { const: false } } }, { paused: false }), ...protectedMutation }) },
    "/api/activity": { get: endpoint("Activity", "listActivity", "List 50 newest audit events", { "200": result("Newest first.", list("AuditEvent"), { items: [] }), ...protectedGet }) },
  },
};
