"use client";
import { Suspense, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Search, MapPin, SlidersHorizontal, Check, FileText } from "lucide-react";
import { mockOpportunities } from "@/lib/mock-data";
import { MatchScore } from "@/components/domain/MatchScore";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useStoredState } from "@/lib/workspace-state";
import { useWorkspace } from "@/components/shell/WorkspaceProvider";
import type { Opportunity } from "@/lib/types";
const empty: Record<string, string> = {};
const statusLabels: Record<string, string> = { PENDING_APPROVAL: "Needs review", QUALIFIED: "Qualified", NEW: "New", APPLIED: "Applied", REPLIED: "Replied", INTERVIEW: "Interview", SKIPPED: "Skipped", PREPARED: "Prepared", CONTACTED: "Contacted" };
function Detail({ opportunity: o, close }: { opportunity: Opportunity; close: () => void }) {
  const [drafts, setDrafts] = useStoredState("application-drafts", empty);
  const [decisions, setDecisions] = useStoredState("decisions", empty);
  const { notify } = useWorkspace();
  const [editing, setEditing] = useState(false);
  const draft = drafts[o.id] ?? "";
  function saveDecision(value: string) { if (setDecisions(previous => ({ ...previous, [o.id]: value }))) notify(value === "reviewed" ? "Marked as reviewed in this browser. No application was sent." : "Opportunity skipped in this preview."); else notify("Could not save. Please check your browser storage."); }
  return <section aria-label="Opportunity details" className="flex h-full min-w-0 flex-col bg-[var(--app-surface)]">
    <div className="flex shrink-0 items-center justify-between border-b border-[var(--app-line)] px-5 py-3"><Button variant="ghost" size="sm" onClick={close}><ArrowLeft size={15} />Back to opportunities</Button><span className="text-[11px] text-[var(--app-muted)]">Sample opportunity</span></div>
    <div className="flex-1 space-y-7 overflow-y-auto p-5 sm:p-7">
      <div><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl border border-[var(--app-line)] text-xl font-medium">{o.companyName[0]}</div><p className="mb-2 text-sm text-[var(--app-muted)]">{o.companyName}</p><h2 className="text-[24px] font-semibold leading-8">{o.title}</h2><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-[var(--app-secondary)]">{o.location && <span className="flex items-center gap-1.5"><MapPin size={13} />{o.location} · {o.workMode}</span>}{o.compensation?.min && <span>{new Intl.NumberFormat("en", { style: "currency", currency: o.compensation.currency ?? "USD", maximumFractionDigits: 0 }).format(o.compensation.min)}{o.compensation.max ? `–${new Intl.NumberFormat("en", { style: "currency", currency: o.compensation.currency ?? "USD", maximumFractionDigits: 0 }).format(o.compensation.max)}` : ""}</span>}</div><span className="mt-4 inline-flex rounded-md border border-[var(--app-line)] px-2 py-1 text-xs capitalize">{decisions[o.id] ?? statusLabels[o.status] ?? o.status.toLowerCase()}</span></div>
      {o.match && <section className="border-t border-[var(--app-line)] pt-6"><h3 className="eyebrow mb-4">Why this might fit</h3><MatchScore match={o.match} size="large" /><p className="mt-3 text-[11px] text-[var(--app-muted)]">Fit score out of 100, not a prediction of an offer.</p></section>}
      <section className="border-t border-[var(--app-line)] pt-6"><h3 className="mb-3 text-sm font-semibold">About the opportunity</h3><p className="text-sm leading-6 text-[var(--app-secondary)]">{o.description}</p><p className="mt-3 text-xs text-[var(--app-muted)]">Source: {o.source}</p>{o.sourceUrl && <a className="mt-3 inline-flex items-center gap-1 text-xs underline underline-offset-4" href={o.sourceUrl} target="_blank" rel="noopener noreferrer">View source <ArrowUpRight size={13} /></a>}</section>
      <section className="border-t border-[var(--app-line)] pt-6"><h3 className="mb-3 flex items-center gap-2 text-sm font-semibold"><FileText size={15} />Application notes</h3>{o.cvUsed && <p className="mb-3 text-xs text-[var(--app-secondary)]">Suggested CV: {o.cvUsed}</p>}<p className="mb-3 text-xs leading-5 text-[var(--app-muted)]">Write and save your draft here. Sending applications becomes available when a live account is connected.</p>{editing ? <textarea autoFocus aria-label="Application draft" rows={6} className="workspace-field" value={draft} onChange={e => { if (!setDrafts(previous => ({ ...previous, [o.id]: e.target.value }))) notify("Could not save the draft."); }} placeholder="Write your application notes…" /> : <p className="whitespace-pre-wrap text-sm leading-6 text-[var(--app-secondary)]">{draft || "No draft added yet."}</p>}<Button className="mt-3" variant="secondary" size="sm" onClick={() => setEditing(!editing)}>{editing ? "Done editing" : draft ? "Edit draft" : "Write a draft"}</Button></section>
    </div>
    <div className="flex shrink-0 flex-wrap items-center justify-between gap-2 border-t border-[var(--app-line)] p-4"><Button variant="ghost" size="sm" onClick={() => saveDecision("skipped")} disabled={decisions[o.id] === "skipped"}>Skip opportunity</Button><Button size="sm" onClick={() => saveDecision("reviewed")} disabled={decisions[o.id] === "reviewed"}><Check size={14} />{decisions[o.id] === "reviewed" ? "Reviewed" : "Mark reviewed"}</Button></div>
  </section>;
}
function Opportunities() {
  const params = useSearchParams(); const router = useRouter();
  const [type, setType] = useState("ALL"); const [query, setQuery] = useState(""); const [strong, setStrong] = useState(params.get("match") === "strong");
  const [decisions] = useStoredState("decisions", empty);
  const selected = mockOpportunities.find(o => o.id === params.get("id"));
  const filtered = mockOpportunities.filter(o => (type === "ALL" || o.type === type) && (!strong || (o.match?.hardRulePass && o.match.score >= 80)) && `${o.title} ${o.companyName} ${o.location}`.toLowerCase().includes(query.toLowerCase()));
  function select(id?: string) { router.push(`/dashboard/opportunities${id ? `?id=${id}` : ""}`, { scroll: false }); }
  return <div className="flex h-full min-h-0">
    <div className={cn("min-w-0 flex-1 flex-col", selected ? "hidden xl:flex" : "flex")}><div className="border-b border-[var(--app-line)] px-5 py-6 sm:px-8"><p className="eyebrow mb-2">Your pipeline</p><h1 className="page-heading">Opportunities</h1><p className="mt-2 text-sm text-[var(--app-muted)]">Find the work worth pursuing.</p><div className="mt-6 flex flex-wrap items-center gap-2"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-lg border border-[var(--app-line)] bg-[var(--app-surface)] px-3"><Search size={15} className="shrink-0 text-[var(--app-muted)]" /><input aria-label="Search opportunities" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search roles or companies" className="h-10 min-w-0 w-full bg-transparent text-sm outline-none" /></label><Button variant={strong ? "brand" : "secondary"} size="sm" aria-pressed={strong} onClick={() => setStrong(!strong)}><SlidersHorizontal size={14} />Strong fit</Button></div><div className="mt-4 flex flex-wrap gap-1">{[["ALL", "All"], ["JOB", "Jobs"], ["CLIENT", "Clients"], ["INBOUND", "Inbound"]].map(([value, label]) => <button key={value} aria-pressed={type === value} onClick={() => setType(value)} className={cn("min-h-10 rounded-lg px-3 text-xs", type === value ? "bg-[var(--app-subtle)] font-semibold" : "text-[var(--app-muted)] hover:text-[var(--app-ink)]")}>{label}</button>)}<span className="ml-auto self-center text-xs text-[var(--app-muted)]">{filtered.length} results</span></div></div>
    <div className="flex-1 overflow-y-auto">{filtered.map(o => <button key={o.id} onClick={() => select(o.id)} aria-current={selected?.id === o.id ? "true" : undefined} className={cn("flex w-full gap-3 border-b border-[var(--app-line)] px-5 py-5 text-left transition-colors hover:bg-[var(--app-subtle)] sm:px-8", selected?.id === o.id && "bg-[var(--app-subtle)]")}><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-[var(--app-line)] bg-[var(--app-surface)] font-medium">{o.companyName[0]}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-[var(--app-muted)]">{o.companyName}</span><span className="text-[11px] capitalize text-[var(--app-secondary)]">{decisions[o.id] ?? statusLabels[o.status] ?? o.status.toLowerCase()}</span></div><h2 className="mt-1 text-[14px] font-medium leading-6">{o.title}</h2><p className="mt-1 text-xs text-[var(--app-muted)]">{o.workMode ?? o.type.toLowerCase()} · {o.location ?? o.source}</p>{o.match && <p className="mt-3 flex items-center gap-2 text-xs text-[var(--app-secondary)]"><span className="font-semibold tabular-nums">{o.match.score}/100</span><span className="truncate">{o.match.hardRulePass ? o.match.matchedSkills.slice(0, 3).join(" · ") : "Outside your preferences"}</span></p>}</div></button>)}{!filtered.length && <div className="p-10 text-center"><h2 className="font-medium">No matching opportunities</h2><p className="mt-2 text-sm text-[var(--app-muted)]">Try a different search or clear your filters.</p><Button variant="secondary" className="mt-4" onClick={() => { setQuery(""); setType("ALL"); setStrong(false); }}>Clear filters</Button></div>}</div></div>
    {selected && <div className="min-w-0 flex-1 xl:max-w-[520px] xl:border-l xl:border-[var(--app-line)]"><Detail key={selected.id} opportunity={selected} close={() => select()} /></div>}
  </div>;
}
export default function OpportunitiesPage() { return <Suspense fallback={<p className="p-6 text-sm">Loading opportunities…</p>}><Opportunities /></Suspense>; }
