"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, FileText, MessageSquare, ArrowUp } from "lucide-react";
import { mockAttentionItems, mockAuditEvents, mockOpportunities, mockConversations } from "@/lib/mock-data";
import { ActivityEvent } from "@/components/domain/ActivityEvent";
import { entityHref, useStoredState } from "@/lib/workspace-state";
import { useWorkspace } from "@/components/shell/WorkspaceProvider";
const emptyDecisions: Record<string, string> = {};
export default function OverviewPage() {
  const { paused } = useWorkspace();
  const [decisions] = useStoredState("decisions", emptyDecisions);
  const attention = mockAttentionItems.filter(item => !decisions[item.entityRef.id]);
  const matches = mockOpportunities.filter(o => o.match?.hardRulePass && o.match.score >= 80);
  return <div className="workspace-page">
    <div className="mb-9 flex items-start justify-between gap-4"><div><p className="eyebrow mb-3">Your daily brief</p><h1 className="page-heading">A little closer to your next move.</h1><p className="mt-3 max-w-xl text-[14px] leading-6 text-[var(--app-secondary)]">Welcome back, Olamide. {attention.length ? <>You have <span className="font-medium text-[var(--app-ink)]">{attention.length} things to review.</span> Start with what matters.</> : "You’re all caught up. Explore your next opportunity."}</p></div><span className="hidden rounded-full border border-[var(--app-line)] px-3 py-1 text-[11px] text-[var(--app-muted)] sm:block">Sample workspace</span></div>
    <section aria-label="Pipeline summary" className="mb-10 grid grid-cols-3 border-y border-[var(--app-line)] py-5 sm:py-6">
      {[["Opportunities", mockOpportunities.length, "/dashboard/opportunities"], ["Strong matches", matches.length, "/dashboard/opportunities?match=strong"], ["Conversations", mockConversations.length, "/dashboard/inbox"]].map(([label, value, href], i) => <Link key={label} href={String(href)} className={`group ${i ? "border-l border-[var(--app-line)] pl-4 sm:pl-8" : "pr-3"}`}><div className="mb-2 flex items-center gap-2 text-[11px] text-[var(--app-muted)] sm:text-xs">{label}<ArrowUpRight size={13} className="hidden opacity-0 group-hover:opacity-100 sm:block" /></div><p className="text-[30px] font-medium leading-none tracking-[-.05em] sm:text-[36px]">{value}</p></Link>)}
    </section>
    <div className="grid gap-12 xl:grid-cols-[minmax(0,1fr)_260px]">
      <div><section aria-labelledby="attention-title"><div className="mb-4 flex items-center justify-between"><h2 id="attention-title" className="text-base font-semibold">Needs your attention <span className="ml-2 text-xs font-normal text-[var(--app-muted)]">{attention.length.toString().padStart(2, "0")}</span></h2><span className="text-[11px] text-[var(--app-muted)]">Suggested next steps</span></div>
        <div className="divide-y divide-[var(--app-line)] border-y border-[var(--app-line)]">{attention.map((item, index) => <Link key={item.id} href={entityHref(item.entityRef)} className="group flex gap-3 py-5 sm:gap-4"><div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-[var(--app-line)] text-[var(--app-secondary)]">{item.urgency === "reply_interview" ? <MessageSquare size={16} /> : <FileText size={16} />}</div><div className="min-w-0 flex-1"><div className="mb-1 flex items-center gap-2"><p className="text-[14px] font-medium leading-6">{item.urgency === "approval_required" ? `Review ${mockOpportunities.find(o => o.id === item.entityRef.id)?.companyName ?? "this opportunity"}` : item.title}</p>{index === 0 && <span className="hidden h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--app-accent)] sm:block" />}</div><p className="max-w-xl text-[13px] leading-[21px] text-[var(--app-muted)]">{item.urgency === "approval_required" ? "Explore the fit, check your application materials, and decide whether to take the next step." : item.description}</p><span className="mt-3 inline-flex items-center gap-2 text-xs font-medium">{item.urgency === "approval_required" ? "Review application" : item.action}<ArrowRight size={13} className="transition-transform group-hover:translate-x-1" /></span></div></Link>)}{!attention.length && <p className="py-8 text-sm text-[var(--app-muted)]">Everything has been reviewed. Your opportunities are still available in the pipeline.</p>}</div>
      </section><section className="mt-9"><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-semibold">Recent activity</h2><Link href="/dashboard/activity" className="flex items-center gap-1 text-xs text-[var(--app-secondary)]">View all <ArrowRight size={13} /></Link></div><div className="space-y-2">{mockAuditEvents.slice(0, 3).map(event => <ActivityEvent key={event.id} event={event} />)}</div></section></div>
      <aside className="space-y-8"><section className="rounded-xl border border-[var(--app-line)] bg-[var(--app-surface)] p-5"><div className="mb-5 flex items-center justify-between"><span className="eyebrow">Worth a look</span><ArrowUpRight size={16} className="text-[var(--app-muted)]" /></div><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--app-subtle)] text-lg font-semibold">S</div><h3 className="text-sm font-semibold">Senior Frontend Engineer</h3><p className="mt-1 text-xs text-[var(--app-muted)]">Stripe · Hybrid</p><p className="mt-4 text-[13px] leading-[21px] text-[var(--app-secondary)]">Your React and design systems experience aligns with this team.</p><div className="mt-4 border-t border-[var(--app-line)] pt-4"><Link href="/dashboard/opportunities?id=opp-001" className="flex items-center justify-between text-xs font-medium">Explore the match <ArrowRight size={14} /></Link></div></section>
      <section><h3 className="mb-4 text-sm font-medium">Make this workspace yours</h3><div className="space-y-1">{[["Review your profile", "/dashboard/profile"], ["Add your documents", "/dashboard/cvs"], ["Set your agent’s boundaries", "/dashboard/agent-rules"]].map(([label, href]) => <Link key={href} href={href} className="flex items-center gap-3 rounded-lg py-2.5 text-xs text-[var(--app-secondary)] hover:text-[var(--app-ink)]"><span className="flex h-5 w-5 items-center justify-center rounded-full border border-[var(--app-line-strong)]"><ArrowUp size={11} className="rotate-45" /></span>{label}</Link>)}</div></section>
      <div className="border-t border-[var(--app-line)] pt-5"><p className="flex items-center gap-2 text-xs font-medium"><Check size={14} />{paused ? "Agent preview paused" : "You have the final say"}</p><p className="mt-2 text-xs leading-5 text-[var(--app-muted)]">{paused ? "Resume from the top bar when you’re ready." : "Review drafts before taking action. This preview does not send messages."}</p></div></aside>
    </div>
  </div>;
}
