"use client";
import { useState } from "react";
import { Sun, Moon, Monitor, Check, Download, RotateCcw } from "lucide-react";
import { useWorkspace } from "@/components/shell/WorkspaceProvider";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { exportWorkspace, resetWorkspace } from "@/lib/workspace-state";
import { removeDocument } from "@/lib/documents";
import { cn } from "@/lib/utils";
export default function SettingsPage() {
  const { theme, setTheme, notify } = useWorkspace();
  const [resetOpen, setResetOpen] = useState(false);
  return <div className="workspace-page !max-w-[900px]">
    <p className="eyebrow mb-3">Make yourself at home</p><h1 className="page-heading">Settings</h1><p className="mt-3 text-sm text-[var(--app-muted)]">A workspace that works the way you do.</p>
    <section className="mt-10 border-t border-[var(--app-line)] py-7"><h2 className="text-base font-semibold">Appearance</h2><p className="mt-2 text-sm text-[var(--app-muted)]">Choose a theme, or follow your device. Your choice is saved automatically.</p><div className="mt-6 grid grid-cols-3 gap-3" role="group" aria-label="Color theme">{([{ value: "light", label: "Light", icon: Sun }, { value: "dark", label: "Dark", icon: Moon }, { value: "system", label: "System", icon: Monitor }] as const).map(({ value, label, icon: Icon }) => <button key={value} aria-pressed={theme === value} onClick={() => setTheme(value)} className={cn("overflow-hidden rounded-xl border p-2 text-left transition-colors sm:p-3", theme === value ? "border-[var(--app-action)]" : "border-[var(--app-line)] hover:border-[var(--app-line-strong)]")}><div aria-hidden="true" className={cn("flex h-20 overflow-hidden rounded-md border sm:h-28", value === "dark" ? "border-[#3a403b] bg-[#171918]" : value === "light" ? "border-[#e4e6e2] bg-[#fafaf9]" : "border-[var(--app-line)] bg-[var(--app-canvas)]")}><div className={cn("w-1/4 border-r", value === "dark" ? "border-[#333a34] bg-[#121513]" : value === "light" ? "border-[#e4e6e2] bg-[#f0f0ed]" : "border-[var(--app-line)] bg-[var(--app-sidebar)]")} /><div className="flex-1 space-y-2 p-3"><div className={cn("h-1.5 w-3/4 rounded", value === "dark" ? "bg-[#a0aaa1]" : value === "light" ? "bg-[#69716c]" : "bg-[var(--app-muted)]")} /><div className="h-1 w-full rounded bg-[#808880]/25" /><div className="h-1 w-2/3 rounded bg-[#808880]/25" /></div></div><span className="mt-3 flex items-center gap-2 text-xs sm:text-sm"><Icon size={15} /><span>{label}</span>{theme === value && <Check size={14} className="ml-auto" />}</span></button>)}</div></section>
    <section className="border-t border-[var(--app-line)] py-7"><h2 className="text-base font-semibold">Workspace data</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[var(--app-muted)]">This is a preview with sample opportunities. Profile edits, drafts, rules, and review decisions stay in this browser. No email account or AI provider is connected.</p><div className="mt-5 flex flex-wrap gap-3"><Button variant="secondary" onClick={() => { try { exportWorkspace(); notify("Your saved workspace data was exported."); } catch { notify("Could not export your workspace. Check browser storage access."); } }}><Download size={15} />Export saved data</Button><Button variant="ghost" onClick={() => setResetOpen(true)}><RotateCcw size={15} />Reset preview</Button></div></section>
    <section className="border-t border-[var(--app-line)] py-7"><h2 className="text-base font-semibold">Account & notifications</h2><p className="mt-2 text-sm leading-6 text-[var(--app-muted)]">Email notifications, account deletion, and provider privacy controls will be available with a live account. There is no active account to configure in this preview.</p></section>
    <Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent><DialogHeader><DialogTitle>Reset this preview?</DialogTitle><DialogDescription>This removes your saved profile edits, drafts, documents, rules, and review decisions from this browser. Your theme preference stays.</DialogDescription></DialogHeader><DialogFooter><Button variant="secondary" onClick={() => setResetOpen(false)}>Cancel</Button><Button onClick={async () => { try { await removeDocument(); resetWorkspace(); setResetOpen(false); notify("Preview reset. Sample data has been restored."); } catch { notify("Could not reset browser data."); } }}>Reset preview</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
