import type {
  Opportunity,
  CV,
  Profile,
  AgentPolicy,
  AuditEvent,
  Conversation,
  Notification,
  Integration,
  DashboardMetrics,
  AttentionItem,
} from "./types";

// ─── Dashboard ───────────────────────────────────────────────

export const mockMetrics: DashboardMetrics = {
  opportunitiesFoundToday: 14,
  highMatches: 5,
  actionsTaken: 3,
  positiveReplies: 2,
  agentStatus: "running",
  lastSyncAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  queueDepth: 7,
  dailyLimitUsed: 3,
  dailyLimitMax: 10,
};

export const mockAttentionItems: AttentionItem[] = [
  {
    id: "att-001",
    urgency: "reply_interview",
    title: "Stripe replied to your application",
    description:
      "Sarah Chen at Stripe is interested in scheduling a technical interview for the Senior Frontend Engineer role.",
    action: "Open conversation",
    entityRef: { type: "conversation", id: "conv-001" },
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "att-002",
    urgency: "approval_required",
    title: "Application ready to send — Vercel",
    description:
      "Pursio prepared a tailored application for Staff Engineer (Platform) at Vercel. Match score 92. Requires your approval before sending.",
    action: "Review & approve",
    entityRef: { type: "opportunity", id: "opp-002" },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "att-003",
    urgency: "approval_required",
    title: "Client outreach ready — TechFlow Ltd",
    description:
      "Pursio drafted a personalized pitch for TechFlow Ltd's e-commerce re-platform project. Awaiting your approval before sending.",
    action: "Review & approve",
    entityRef: { type: "opportunity", id: "opp-008" },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "att-004",
    urgency: "reply_interview",
    title: "Linear — question about availability",
    description:
      "Recruiter at Linear asked about your earliest start date and preferred interview times.",
    action: "Draft reply",
    entityRef: { type: "conversation", id: "conv-002" },
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Opportunities ───────────────────────────────────────────

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-001",
    type: "JOB",
    companyName: "Stripe",
    companyDomain: "stripe.com",
    title: "Senior Frontend Engineer",
    description:
      "Build the next generation of Stripe's dashboard. You'll work on React, TypeScript, and internal design systems used by millions of businesses.",
    location: "San Francisco, CA",
    workMode: "hybrid",
    compensation: { min: 180000, max: 230000, currency: "USD" },
    source: "Gmail alert",
    sourceUrl: "https://stripe.com/jobs/listing/senior-frontend",
    status: "REPLIED",
    discoveredAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    match: {
      score: 94,
      hardRulePass: true,
      matchedSkills: ["React", "TypeScript", "Design Systems"],
      gaps: ["GraphQL (preferred)"],
      unknowns: [],
      explanation:
        "Strong skill alignment with React and TypeScript. Design systems experience matches their team focus. Compensation above floor.",
    },
    cvUsed: "Frontend-focused",
    requiresAttention: true,
    attentionReason: "Recruiter replied — interested in interview",
  },
  {
    id: "opp-002",
    type: "JOB",
    companyName: "Vercel",
    companyDomain: "vercel.com",
    title: "Staff Engineer, Platform",
    description:
      "Shape the future of web deployment infrastructure. Work on Next.js ecosystem, edge runtimes, and developer tooling.",
    location: "Remote",
    workMode: "remote",
    compensation: { min: 200000, max: 260000, currency: "USD" },
    source: "Recruiter email",
    sourceUrl: "https://vercel.com/careers",
    status: "PENDING_APPROVAL",
    discoveredAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    match: {
      score: 92,
      hardRulePass: true,
      matchedSkills: ["Next.js", "TypeScript", "Node.js", "Infrastructure"],
      gaps: ["Rust (preferred)"],
      unknowns: ["Team size"],
      explanation:
        "Excellent alignment with Next.js expertise. Remote work satisfies location preference. Compensation well above floor.",
    },
    cvUsed: "Full-stack",
    requiresAttention: true,
    attentionReason: "Application ready — awaiting approval",
  },
  {
    id: "opp-003",
    type: "JOB",
    companyName: "Linear",
    companyDomain: "linear.app",
    title: "Software Engineer, Product",
    description:
      "Work on Linear's core product experience. Focus on performance, real-time collaboration, and a delightful user interface.",
    location: "Remote",
    workMode: "remote",
    compensation: { min: 160000, max: 200000, currency: "USD" },
    source: "Gmail alert",
    status: "APPLIED",
    discoveredAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    match: {
      score: 88,
      hardRulePass: true,
      matchedSkills: ["React", "TypeScript", "Performance"],
      gaps: ["Elixir (nice to have)"],
      unknowns: [],
      explanation:
        "Strong product engineering alignment. Real-time systems experience matches their collaboration features.",
    },
    cvUsed: "Full-stack",
    requiresAttention: true,
    attentionReason: "Recruiter asked about availability",
  },
  {
    id: "opp-004",
    type: "JOB",
    companyName: "Figma",
    companyDomain: "figma.com",
    title: "Senior Software Engineer, Dev Mode",
    description:
      "Build tools that bridge design and engineering. Work on code generation, design token extraction, and developer integrations.",
    location: "San Francisco, CA",
    workMode: "hybrid",
    compensation: { min: 190000, max: 240000, currency: "USD" },
    source: "Gmail alert",
    status: "QUALIFIED",
    discoveredAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    match: {
      score: 85,
      hardRulePass: true,
      matchedSkills: ["TypeScript", "React", "Developer Tools"],
      gaps: ["WebAssembly (preferred)", "C++ (nice to have)"],
      unknowns: [],
      explanation:
        "Dev Mode is highly relevant given your tooling experience. Design system background aligns well.",
    },
    cvUsed: "Frontend-focused",
  },
  {
    id: "opp-005",
    type: "JOB",
    companyName: "Notion",
    companyDomain: "notion.so",
    title: "Frontend Engineer",
    description: "Build rich content editing experiences in Notion's collaborative workspace.",
    location: "New York, NY",
    workMode: "hybrid",
    compensation: { min: 150000, max: 190000, currency: "USD" },
    source: "Gmail alert",
    status: "NEW",
    discoveredAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    match: {
      score: 78,
      hardRulePass: true,
      matchedSkills: ["React", "TypeScript", "Rich Text"],
      gaps: ["ProseMirror (preferred)"],
      unknowns: ["Compensation confirmed"],
      explanation: "Good alignment. Rich text editing is learnable. Compensation at floor.",
    },
  },
  {
    id: "opp-006",
    type: "JOB",
    companyName: "Anthropic",
    companyDomain: "anthropic.com",
    title: "Product Engineer",
    description: "Work on Claude.ai's consumer product and developer platform.",
    location: "San Francisco, CA",
    workMode: "onsite",
    compensation: { min: 200000, max: 280000, currency: "USD" },
    source: "Recruiter email",
    status: "QUALIFIED",
    discoveredAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    match: {
      score: 82,
      hardRulePass: false,
      matchedSkills: ["React", "TypeScript", "API Design"],
      gaps: ["Python (preferred for ML adjacent work)"],
      unknowns: [],
      explanation:
        "Hard rule: onsite only does not match remote preference. Score reflects skill fit only.",
    },
  },
  {
    id: "opp-007",
    type: "JOB",
    companyName: "Retool",
    companyDomain: "retool.com",
    title: "Senior Engineer, Integrations",
    description: "Build and maintain Retool's integrations marketplace. 400+ connectors.",
    location: "Remote",
    workMode: "remote",
    compensation: { min: 170000, max: 210000, currency: "USD" },
    source: "Gmail alert",
    status: "SKIPPED",
    discoveredAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    match: {
      score: 61,
      hardRulePass: true,
      matchedSkills: ["Node.js", "APIs"],
      gaps: ["Java", "Go"],
      unknowns: ["Tech stack confirmation"],
      explanation: "Below auto-qualify threshold. Skill gaps in required languages are significant.",
    },
  },
  {
    id: "opp-008",
    type: "CLIENT",
    companyName: "TechFlow Ltd",
    companyDomain: "techflow.io",
    title: "E-commerce Platform Re-build",
    description:
      "Mid-size UK retailer seeking a frontend engineer to re-platform their e-commerce storefront from Magento to Next.js. 3-month contract.",
    location: "Remote",
    workMode: "remote",
    source: "Gmail direct message",
    status: "PENDING_APPROVAL",
    discoveredAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    match: {
      score: 89,
      hardRulePass: true,
      matchedSkills: ["Next.js", "TypeScript", "E-commerce"],
      gaps: [],
      unknowns: ["Rate / budget"],
      explanation:
        "Strong fit. Next.js expertise directly maps. Remote contract aligns with preferences.",
    },
    requiresAttention: true,
    attentionReason: "Outreach ready — awaiting approval",
  },
  {
    id: "opp-009",
    type: "INBOUND",
    companyName: "StartupXYZ",
    title: "Contract Web Development",
    description: "Inbound request for a landing page and marketing site rebuild.",
    location: "Remote",
    workMode: "remote",
    source: "Direct email",
    status: "NEW",
    discoveredAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    match: {
      score: 72,
      hardRulePass: true,
      matchedSkills: ["Next.js", "React", "Tailwind"],
      gaps: [],
      unknowns: ["Budget", "Timeline"],
      explanation: "Straightforward fit. Budget and timeline unknown — qualify before proceeding.",
    },
  },
  {
    id: "opp-010",
    type: "JOB",
    companyName: "GitHub",
    companyDomain: "github.com",
    title: "Staff Frontend Engineer, Copilot",
    description:
      "Lead frontend architecture for GitHub Copilot's IDE integrations and web experience.",
    location: "Remote",
    workMode: "remote",
    compensation: { min: 210000, max: 270000, currency: "USD" },
    source: "Gmail alert",
    status: "PREPARED",
    discoveredAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    match: {
      score: 91,
      hardRulePass: true,
      matchedSkills: ["TypeScript", "React", "Developer Tools", "API Design"],
      gaps: ["VS Code Extension API (learnable)"],
      unknowns: [],
      explanation:
        "Excellent match. Developer tooling background directly relevant. Copilot team focus aligns with AI interest.",
    },
    cvUsed: "Full-stack",
  },
];

// ─── CVs ─────────────────────────────────────────────────────

export const mockCVs: CV[] = [
  {
    id: "cv-001",
    label: "Full-stack",
    fileName: "resume_fullstack_2024.pdf",
    version: 3,
    isDefault: true,
    roleFocus: "Full-stack engineering, API design, systems",
    skills: ["TypeScript", "React", "Node.js", "PostgreSQL", "Next.js", "Docker"],
    lastUsed: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    usageCount: 12,
    uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: "ready",
  },
  {
    id: "cv-002",
    label: "Frontend-focused",
    fileName: "resume_frontend_2024.pdf",
    version: 2,
    isDefault: false,
    roleFocus: "Frontend, React, design systems, performance",
    skills: ["React", "TypeScript", "CSS", "Tailwind", "Design Systems", "Accessibility"],
    lastUsed: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    usageCount: 7,
    uploadedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: "ready",
  },
  {
    id: "cv-003",
    label: "General",
    fileName: "resume_general_2024.pdf",
    version: 1,
    isDefault: false,
    roleFocus: "Broad engineering, startups, generalist roles",
    skills: ["JavaScript", "Python", "React", "Node.js", "SQL", "Git"],
    usageCount: 2,
    uploadedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    status: "ready",
  },
];

// ─── Profile ─────────────────────────────────────────────────

export const mockProfile: Profile = {
  headline: "Senior Software Engineer",
  summary:
    "6 years of experience building web products at scale. Focused on TypeScript, React, and developer tooling. Looking for senior to staff IC roles at product-focused companies.",
  yearsExperience: 6,
  targetRoles: ["Senior Software Engineer", "Staff Engineer", "Frontend Engineer", "Full-stack Engineer"],
  skills: [
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "PostgreSQL",
    "Docker",
    "REST APIs",
    "GraphQL",
    "Tailwind CSS",
    "Design Systems",
    "Testing",
    "CI/CD",
  ],
  locations: ["Remote", "San Francisco, CA", "New York, NY"],
  workModes: ["remote", "hybrid"],
  compensationMin: 150000,
  compensationCurrency: "USD",
  links: {
    github: "https://github.com/owner",
    portfolio: "https://owner.dev",
    linkedin: "https://linkedin.com/in/owner",
  },
  facts: [
    { id: "f-001", type: "employer", value: "Acme Corp (2021–present)", verified: true, evidenceSource: "cv-001" },
    { id: "f-002", type: "employer", value: "BuildCo (2018–2021)", verified: true, evidenceSource: "cv-001" },
    { id: "f-003", type: "education", value: "BSc Computer Science, University of Example", verified: true, evidenceSource: "cv-001" },
    { id: "f-004", type: "skill", value: "TypeScript — 5 years", verified: true, evidenceSource: "cv-001" },
    { id: "f-005", type: "skill", value: "React — 5 years", verified: true, evidenceSource: "cv-001" },
    { id: "f-006", type: "achievement", value: "Led migration of monolith to microservices, 40% latency reduction", verified: true, evidenceSource: "cv-001" },
  ],
};

// ─── Agent Policy ─────────────────────────────────────────────

export const mockPolicy: AgentPolicy = {
  globalMode: "auto",
  minMatchScore: 70,
  autoSendMinScore: 85,
  maxDailyOutreach: 10,
  compensationMin: 150000,
  requireApprovalFor: ["salary_negotiation", "interview_scheduling", "contracts", "identity_documents"],
  exclusions: ["blockchain-only companies", "adtech/surveillance companies"],
  quietHoursStart: "22:00",
  quietHoursEnd: "08:00",
};

// ─── Audit Events ─────────────────────────────────────────────

export const mockAuditEvents: AuditEvent[] = [
  {
    id: "ae-001",
    eventType: "opportunity.discovered",
    actor: "agent",
    entityType: "opportunity",
    entityId: "opp-009",
    traceId: "tr-a1b2c3",
    details: { source: "Gmail", subject: "New project inquiry", classification: "CLIENT" },
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: "ae-002",
    eventType: "opportunity.scored",
    actor: "agent",
    entityType: "opportunity",
    entityId: "opp-009",
    traceId: "tr-a1b2c3",
    details: { score: 72, hardRulePass: true, model: "gpt-4o" },
    createdAt: new Date(Date.now() - 19 * 60 * 1000).toISOString(),
  },
  {
    id: "ae-003",
    eventType: "gmail.synced",
    actor: "agent",
    entityType: "integration",
    traceId: "tr-d4e5f6",
    details: { messagesProcessed: 6, newOpportunities: 1, newReplies: 1 },
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },
  {
    id: "ae-004",
    eventType: "reply.detected",
    actor: "agent",
    entityType: "conversation",
    entityId: "conv-001",
    traceId: "tr-g7h8i9",
    details: { intent: "interested", company: "Stripe", requiresAttention: true },
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "ae-005",
    eventType: "application.prepared",
    actor: "agent",
    entityType: "opportunity",
    entityId: "opp-002",
    traceId: "tr-j1k2l3",
    details: { cv: "Full-stack", policyDecision: "REQUIRE_APPROVAL", reason: "score below auto-send floor" },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ae-006",
    eventType: "opportunity.discovered",
    actor: "agent",
    entityType: "opportunity",
    entityId: "opp-005",
    traceId: "tr-m4n5o6",
    details: { source: "Gmail alert", subject: "Frontend Engineer @ Notion" },
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ae-007",
    eventType: "opportunity.scored",
    actor: "agent",
    entityType: "opportunity",
    entityId: "opp-005",
    traceId: "tr-m4n5o6",
    details: { score: 78, hardRulePass: true, model: "gpt-4o" },
    createdAt: new Date(Date.now() - 58 * 60 * 1000).toISOString(),
  },
  {
    id: "ae-008",
    eventType: "opportunity.skipped",
    actor: "agent",
    entityType: "opportunity",
    entityId: "opp-007",
    traceId: "tr-p7q8r9",
    details: { reason: "score 61, below min threshold 70", score: 61 },
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ae-009",
    eventType: "application.sent",
    actor: "agent",
    entityType: "opportunity",
    entityId: "opp-003",
    traceId: "tr-s1t2u3",
    details: { channel: "email", policyDecision: "AUTO_EXECUTE", cv: "Full-stack", score: 88 },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Conversations ────────────────────────────────────────────

export const mockConversations: Conversation[] = [
  {
    id: "conv-001",
    opportunityId: "opp-001",
    companyName: "Stripe",
    role: "Senior Frontend Engineer",
    lastMessage:
      "Hi, I'm Sarah from Stripe's recruiting team. We reviewed your application and would love to schedule a technical screen. Are you available this week?",
    lastMessageAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    intent: "interview",
    needsAttention: true,
    messageCount: 3,
  },
  {
    id: "conv-002",
    opportunityId: "opp-003",
    companyName: "Linear",
    role: "Software Engineer, Product",
    lastMessage:
      "Thanks for applying! What's your earliest available start date, and do you have a preference for interview timing?",
    lastMessageAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    intent: "question",
    needsAttention: true,
    messageCount: 2,
  },
  {
    id: "conv-003",
    opportunityId: "opp-010",
    companyName: "GitHub",
    role: "Staff Frontend Engineer, Copilot",
    lastMessage:
      "Thank you for your application. We'll be reviewing submissions over the next two weeks.",
    lastMessageAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    intent: "neutral",
    needsAttention: false,
    messageCount: 1,
  },
];

// ─── Notifications ────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    type: "high_value",
    title: "Stripe recruiter replied",
    body: "Sarah Chen at Stripe is interested in scheduling a technical interview.",
    entityRef: { type: "conversation", id: "conv-001" },
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-002",
    type: "approval",
    title: "Approval needed — Vercel application",
    body: "Application ready for Staff Engineer, Platform at Vercel. Score 92.",
    entityRef: { type: "opportunity", id: "opp-002" },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-003",
    type: "approval",
    title: "Approval needed — TechFlow Ltd pitch",
    body: "Client outreach ready for TechFlow Ltd e-commerce project.",
    entityRef: { type: "opportunity", id: "opp-008" },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-004",
    type: "info",
    title: "14 opportunities found today",
    body: "Pursio found 14 opportunities — 5 high matches. 3 applications prepared.",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    readAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Integration ──────────────────────────────────────────────

export const mockIntegrations: Integration[] = [
  {
    id: "int-001",
    provider: "gmail",
    status: "connected",
    lastSyncAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    scopes: ["gmail.readonly", "gmail.send", "gmail.compose"],
    email: "owner@gmail.com",
  },
];
